APM-1120 Remove duplicate steps

diff --git a/az/templates/pre-tasks.yml b/az/templates/pre-tasks.yml
--- a/az/templates/pre-tasks.yml
+++ b/az/templates/pre-tasks.yml
@@ -6,6 +6,14 @@ steps:
 
   - template: ../components/setup-utils.yml
 
+  - bash: |
+      set -euo pipefail
+      echo "!!! If you get an error here, it is because '$(SERVICE_NAME)' is not the source alias name of the artifact"
+      export SERVICE_ARTIFACT_NAME=`ls $(Pipeline.Workspace)/$(SERVICE_NAME)`
+      echo "##vso[task.setvariable variable=SERVICE_ARTIFACT_NAME]$SERVICE_ARTIFACT_NAME"
+      echo "Set Artifact Name of: $SERVICE_ARTIFACT_NAME"
+    displayName: 'Set SERVICE_ARTIFACT_NAME'
+
   - template: ../components/get-mfa-code.yml
     parameters:
       apigeeOTPKey: $(APIGEE_OTP_KEY)
